spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/playgame_store
    username: postgres
    password: 1984
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: anastasiamoon109@gmail.com
    password: "tglknqhkggrfqxds"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  api-base-url: http://localhost:8080  # Для деплоя: https://api.yoursite.com
  email-verification:
    send-enabled: true
    from: anastasiamoon109@gmail.com
    token-ttl-minutes: 30

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE