INSERT INTO buckets (id, account_id, date_added, type) VALUES
                                                           (1, 1, NOW(), 'BUYLIST'),
                                                           (2, 1, NOW(), 'WISHLIST'),
                                                           (3, 2, '2021-06-15 14:30:00', 'BUYLIST'),
                                                           (4, 2, '2021-06-15 14:30:00', 'WISHLIST'),
                                                           (5, 3, '2022-09-22 09:45:00', 'BUYLIST'),
                                                           (6, 3, '2022-09-22 09:45:00', 'WISHLIST'),
                                                           (7, 4, NOW(), 'BUYLIST'),
                                                           (8, 4, NOW(), 'WISHLIST'),
                                                           (9, 5, '2023-01-10 12:00:00', 'BUYLIST'),
                                                           (10, 5, '2023-01-10 12:00:00', 'WISHLIST'),
                                                           (11, 6, '2020-11-03 18:20:00', 'BUYLIST'),
                                                           (12, 6, '2020-11-03 18:20:00', 'WISHLIST'),
                                                           (13, 7, NOW(), 'BUYLIST'),
                                                           (14, 7, NOW(), 'WISHLIST'),
                                                           (15, 8, '2024-04-12 17:05:00', 'BUYLIST'),
                                                           (16, 8, '2024-04-12 17:05:00', 'WISHLIST'),
                                                           (17, 9, NOW(), 'BUYLIST'),
                                                           (18, 9, NOW(), 'WISHLIST'),
                                                           (19, 10, '2025-02-28 21:15:00', 'BUYLIST'),
                                                           (20, 10, '2025-02-28 21:15:00', 'WISHLIST'),
                                                           (21, 11, NOW(), 'BUYLIST'),
                                                           (22, 11, NOW(), 'WISHLIST'),
                                                           (23, 12, '2021-07-19 08:30:00', 'BUYLIST'),
                                                           (24, 12, '2021-07-19 08:30:00', 'WISHLIST'),
                                                           (25, 13, '2023-08-25 16:10:00', 'BUYLIST'),
                                                           (26, 13, '2023-08-25 16:10:00', 'WISHLIST'),
                                                           (27, 14, NOW(), 'BUYLIST'),
                                                           (28, 14, NOW(), 'WISHLIST'),
                                                           (29, 15, '2022-12-30 14:40:00', 'BUYLIST'),
                                                           (30, 15, '2022-12-30 14:40:00', 'WISHLIST'),
                                                           (31, 16, NOW(), 'BUYLIST'),
                                                           (32, 16, NOW(), 'WISHLIST'),
                                                           (33, 17, '2020-05-05 19:00:00', 'BUYLIST'),
                                                           (34, 17, '2020-05-05 19:00:00', 'WISHLIST'),
                                                           (35, 18, NOW(), 'BUYLIST'),
                                                           (36, 18, NOW(), 'WISHLIST'),
                                                           (37, 19, NOW(), 'BUYLIST'),
                                                           (38, 19, NOW(), 'WISHLIST'),
                                                           (39, 20, NOW(), 'BUYLIST'),
                                                           (40, 20, NOW(), 'WISHLIST'),
                                                           (41, 21, '2022-02-14 10:50:00', 'BUYLIST'),
                                                           (42, 21, '2022-02-14 10:50:00', 'WISHLIST'),
                                                           (43, 22, NOW(), 'BUYLIST'),
                                                           (44, 22, NOW(), 'WISHLIST'),
                                                           (45, 23, '2023-11-07 15:35:00', 'BUYLIST'),
                                                           (46, 23, '2023-11-07 15:35:00', 'WISHLIST'),
                                                           (47, 24, '2021-03-28 11:20:00', 'BUYLIST'),
                                                           (48, 24, '2021-03-28 11:20:00', 'WISHLIST'),
                                                           (49, 25, NOW(), 'BUYLIST'),
                                                           (50, 25, NOW(), 'WISHLIST'),
                                                           (51, 26, '2024-06-01 17:50:00', 'BUYLIST'),
                                                           (52, 26, '2024-06-01 17:50:00', 'WISHLIST'),
                                                           (53, 27, '2020-04-20 22:10:00', 'BUYLIST'),
                                                           (54, 27, '2020-04-20 22:10:00', 'WISHLIST'),
                                                           (55, 28, NOW(), 'BUYLIST'),
                                                           (56, 28, NOW(), 'WISHLIST'),
                                                           (57, 29, NOW(), 'BUYLIST'),
                                                           (58, 29, NOW(), 'WISHLIST'),
                                                           (59, 30, NOW(), 'BUYLIST'),
                                                           (60, 30, NOW(), 'WISHLIST'),
                                                           (61, 31, NOW(), 'BUYLIST'),
                                                           (62, 31, NOW(), 'WISHLIST'),
                                                           (63, 32, NOW(), 'BUYLIST'),
                                                           (64, 32, NOW(), 'WISHLIST'),
                                                           (65, 33, NOW(), 'BUYLIST'),
                                                           (66, 33, NOW(), 'WISHLIST'),
                                                           (67, 34, NOW(), 'BUYLIST'),
                                                           (68, 34, NOW(), 'WISHLIST'),
                                                           (69, 35, NOW(), 'BUYLIST'),
                                                           (70, 35, NOW(), 'WISHLIST'),
                                                           (71, 36, NOW(), 'BUYLIST'),
                                                           (72, 36, NOW(), 'WISHLIST'),
                                                           (73, 37, NOW(), 'BUYLIST'),
                                                           (74, 37, NOW(), 'WISHLIST'),
                                                           (75, 38, NOW(), 'BUYLIST'),
                                                           (76, 38, NOW(), 'WISHLIST'),
                                                           (77, 39, NOW(), 'BUYLIST'),
                                                           (78, 39, NOW(), 'WISHLIST'),
                                                           (79, 40, NOW(), 'BUYLIST'),
                                                           (80, 40, NOW(), 'WISHLIST');

